export const GET_EVENTS = "GET_EVENTS";

export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT";

export const GET_MATCHES_FROM_USER = "GET_MATCHES_FROM_USER";

export const GET_MATCHES_FROM_EVENT = "GET_MATCHES_FROM_EVENT";

export const CREATE_MATCH = "CREATE_MATCH";

export const TOGGLE_AUTH = "TOGGLE_AUTH";

export const SET_THE_USER = "SET_USER";

export const GET_EVENTS_FROM_USER = "GET_EVENTS_FROM_USER";

export const UPDATE_EVENT = "UPDATE_EVENT";

export const CREATE_EVENT = "CREATE_EVENT";

export const DELETE_EVENT = "DELETE_EVENT";

export const GET_ALL_USERS = "GET_ALL_USERS";

export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
